version: 2
project_name: sla-monitor

builds:
  - binary: sla-monitor
    main: ./cmd/sla-monitor/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}.tar.gz"
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: merdincz
    name: sla-monitor

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
